spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: cy414ljh212,,,
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.duing.model
